apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctcf-narrowpeak-pvc
spec:
  storageClassName: zanglab-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: ctcf-narrowpeak-pv