apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctcf-pg-dumps-pvc
  labels:
    app: ctcfexplorer
spec:
  storageClassName: zanglab-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: ctcf-pg-dumps-pv