apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.org/websocket-services: "ctcfexplorer"
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.org/proxy-connect-timeout: "600s"
    nginx.org/proxy-read-timeout: "600s"
    nginx.org/proxy-send-timeout: "600s"
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
  name: ctcfexplorer-ingress
  namespace: zanglab
spec:
  rules:
    - host: ctcfexplorer.pods.uvarc.io
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ctcfexplorer
                port:
                  number: 5000
  tls:
    - hosts:
        - ctcfexplorer.pods.uvarc.io
      secretName: ctcfexplorer-nginx-tls-ingress-secret