name: Docker Build CI

on:
  push:
    branches:
      - 'develop'
      - 'main'
    tags:
      - 'prod-*.*'
  workflow_dispatch:

permissions:
  contents: write  # Allows pushing to the repo

jobs:
  build-for-git:
    runs-on: ubuntu-latest
    env:
      GHCR_REPO: ghcr.io/${{ github.repository_lower }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

#      - name: Set the env
#        id: set_env
#        run: echo "BUILD_PROJ=ctcfexplorer" >> $GITHUB_ENV

      - name: Extract tag name for prod release
        if: startsWith(github.ref, 'refs/tags/prod-')
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
           yq eval ".image.tag = \"${TAG_NAME}\"" -i kubernetes/ctcfexplorer/values.yaml
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push service for non main branch
        if: github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/prod-')
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.GHCR_REPO }}:${{ github.ref_name }}

      - name: Build and push service for main branch
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.GHCR_REPO }}:${{ github.ref_name }}
            ${{ env.GHCR_REPO }}:latest

      - name: Build and push service for prod tag
        if: startsWith(github.ref, 'refs/tags/prod-')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.GHCR_REPO }}:${{ env.TAG_NAME }}

      - name: Push Prod Version to main branch
        if: startsWith(github.ref, 'refs/tags/prod-')
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[skip ci] Update Version to Helm - ${{ env.TAG_NAME }}"
          branch: main
          file_pattern: 'kubernetes/gauss-app-runner/values.yaml'
          commit_user_name: GitHub Actions Bot
          commit_user_email: github@virginia.edu
          commit_author: GitHub Actions <github@virginia.edu>
